name: CIS-CICD

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create virtual machine
        run: |
          az vm create \
            --resource-group Test \
            --name cis-test1 \
            --image UbuntuLTS \
            --admin-username azureuser \
            --admin-password Password@123\
            --size Standard_B2s \
            --storage-sku Standard_LRS \
            --data-disk-sizes-gb 50 \
            --public-ip-address-allocation static \
            --nsg-rule SSH \
            --output table

      - name: Update and patch VM
        run: |
          az vm run-command invoke \
            --resource-group Test \
            --name cis-test1 \
            --command-id RunShellScript \
            --scripts "sudo yum update -y" \
            --output table



  install:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install the GPG key
        run: |
          az vm run-command invoke \
          --resource-group Test \
          --name cis-test1 \
          --command-id RunShellScript \
          --scripts "su -c curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg"
