name: Install Wazuh Agent on Azure VM

on:
  workflow_dispatch:


jobs:
  pull-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: cis-blacklist.conf
          remote: etc/modprobe.d/cis-blacklist.conf
          host: 13.92.170.31
