name: Install Wazuh Agent on Azure VM

on:
  workflow_dispatch:


jobs:
  pull-build:
    runs-on: cis-runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Run LS
        run: sudo ls -a
        
      - name: Create virtual machine
        run: |
          az vm create \
            --resource-group Test \
            --name cis-test10 \
            --image UbuntuLTS \
            --admin-username azureuser \
            --admin-password Password@123\
            --size Standard_B2s \
            --storage-sku Standard_LRS \
            --data-disk-sizes-gb 50 \
            --nsg-rule SSH


  #    - name: Copy single file to remote
  #       uses: garygrossgarten/github-action-scp@release
  #      with:
  #        local: cis-blacklist.conf
  #        remote: cis-blacklist.conf
  #        host: 13.92.170.31
  #        username: azureuser
  #        password: Password@123
          
  #    - name: Copy to etc
  #      uses: appleboy/ssh-action@master
  #      with:
  #        host: 13.92.170.31
  #        username: azureuser
  #        password: Password@123
  #        script: |
  #         sudo mv cis-blacklist.conf /etc/modprobe.d/
