name: Install Wazuh Agent on Azure VM

on:
  workflow_dispatch:

jobs:
  install-wazuh-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}

      - name: SSH to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: 172.174.216.190
          username: azureadmin
          password: Password12345
          script: |
            whoami
            wget -O /tmp/wazuh.gpg https://packages.wazuh.com/key/GPG-KEY-WAZUH
            sudo apt-key add /tmp/wazuh.gpg
            echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | sudo tee /etc/apt/sources.list.d/wazuh.list
            sudo apt update
            sudo apt install -y wazuh-agent
