name: CIS-CICD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Create virtual machine
        run: |
          az vm create \
            --resource-group Test \
            --name cis-test-nginx \
            --image /subscriptions/384f2700-6afb-42c8-886e-d939e5068982/resourceGroups/Test/providers/Microsoft.Compute/images/cis-test-nginx-image \
            --admin-username azureuser \
            --admin-password Password@123\
            --size Standard_B2s \
            --storage-sku Standard_LRS \
            --data-disk-sizes-gb 50 \
            --public-ip-address-allocation static \
            --nsg-rule SSH \
            --output table

      - name: Update & Patch
        run: |
          sudo apt -y update && sudo apt -y upgrade


  install-wazuh-agent:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GPG Key
        run: |
          sudo curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg

      - name: Add the Repo
        run: |
          sudo echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list

      - name: Test install NGINX
        run: |
          sudo apt -y install nginx

      - name: Update
        run: |
          sudo apt -y update


 #     - name: Deallocate VM
 #       run: az vm deallocate --resource-group Test --name cis-test-nginx


#      - name: Cleanup resources
#        run: |
#          az group delete --name Test --yes --no-wait
