name: Build Azure Ubuntu VM with Wazuh Agent

on:
  push:
    branches:
      - main

jobs:
  build-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checout Repo
        uses: actions/checkout@v2


      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
          
      - name: List files
        run: ls -l
        
      - name: Copy SSH key
        run: |
          az vm user update \
            --resource-group Test \
            --name ssh-test1 \
            --username azureuser \
            --ssh-key-value "$(cat${GITHUB_WORKSPACE}/id_rsa.pub)"


     # - name: Add id_rsa.pub
     #   run: |
     #     cat ${{ github.workspace }}/id_rsa.pub | ssh -o "StrictHostKeyChecking=no" -i ${{ secrets.SSH_PRIVATE_KEY }} azureuser@13.92.170.31 'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys'
